<div class="container">
    <h1>Kytschi</h1>
    <h2>Where do you want to go?</h2>
    <img src="<?= $this->tengu->theme->getAsset('illustration-gustavo-viselner-03.jpg'); ?>">
    <p>
        <a href="https://past.kytschi.com">The Past</a>
        <a href="https://future.kytschi.com">The Future</a>
    </p>
    <small>art by Gustavo Viselner</small>
</div>
<audio controls autoplay>
    <source src="<?= $this->tengu->theme->getAsset('gigawatts.mp3'); ?>" type="audio/mpeg">
    Your browser can't play the background tune :-(
</audio> 