<?php
use Kytschi\Tengu\Helpers\DateHelper;
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="referrer" content="origin">
		<meta name="robots" content="<?= $page->robots; ?>">
        <meta name="description" content="<?= $page->meta_description; ?>">
        <meta name="keywords" content="<?= $page->meta_keywords; ?>">
        <meta name="author" content="<?= $page->meta_author; ?>">
		<meta name="revised" content="<?= DateHelper::meta($page->page_updated); ?>">

        <title><?= (!empty($page->name) ? $page->name . ' - ' : '')  . $this->tengu->settings->name;?></title>

        <link rel="stylesheet" href="<?= $this->tengu->theme->getCSS('theme.css'); ?>">
        <link rel="icon" href="<?= $this->tengu->theme->getAsset('favicon.ico'); ?>" sizes="64x64">

        <link rel="canonical" href="<?= $this->tengu->canonicalUrl(); ?>">
        <link rel="author" href="/humans.txt">
    </head>
    <body>
        <main>
            <?= $this->getContent(); ?>
        </main>
	</body>
</html>
