<?php
use Kytschi\Tengu\Helpers\DateHelper;
?>
<div id="page">
    <h2><?= !empty($page->slogan) ? $page->slogan : $page->name; ?></h2>
    <?php
    if ($page->content) {
        ?>
        <section>
            <?= $page->content; ?>
        </section>
        <?php
    }
    $page_num = 1;
    if (!empty($_GET['page'])) {
        $page_num = intval($_GET['page']);
    }
    $category_items = $this->tengu->findCategoryItems([
        'where' => 'pages.type="blog-post" AND pages.status="active"',
        'category_id' => $page->id,
        'pagination' => [
            'page' => $page_num,
            'limit' => 30
        ],
        'order' => 'pages.created_at DESC'
    ]);
    if ($category_items->total_items) {
    ?>
        <div class="tiles">
        <?php
        foreach ($category_items->getItems() as $item) {
            ?>
            <div class="tile">
                <h4><?= $item->name; ?></h4>
                <?php
                if ($item->type == 'blog-post' || $item->type == 'blog-post-category') {
                    ?>
                    <p class="post-date">
                        <?= DateHelper::prettyFull($item->created_at, false); ?>
                    </p>
                    <?php
                }
                if ($item->cover_image) {
                    ?>
                    <p class="tile-img">
                        <img 
                            src="<?=$item->cover_image->url;?>"
                            title="<?= $item->name; ?>"
                            alt="<?= $item->cover_image->label; ?>">
                    </p>
                    <?php
                }
                ?>
                <p>
                    <?= $item->summary; ?>
                </p>
                <p>
                    <a 
                        href="<?= !empty($item->canonical_url) ? $item->canonical_url : $item->url; ?>"
                        class="button" 
                        <?= strpos($item->url, 'http') ? ' target="_blank"' : ''; ?>
                        title="I want to check out <?= $item->name; ?>">
                        <?php
                        switch ($item->type) {
                            case 'blog-post':
                                echo 'Show me more';
                                break;
                            case 'blog-post-category':
                                echo 'Show me more';
                                break;
                            default:
                                echo 'Take me to it';
                                break;
                        }
                        ?>
                    </a>
                </p>
                </div>
            <?php
        }
        ?>
        </div>
        <div class="row">
            <div class="col-12">
                <?php
                    echo $this->partial(
                        'common/pagination',
                        [
                            'data' => $category_items,
                            'url' => $page->url
                        ]
                    );
                ?>
                </div>
        </div>
    <?php
    }
    else {
        ?>
        <div class="row">
            <p class="h4">No posts yet.</p>
        </div>
        <?php
    }
    if (count($page->tags)) {
        ?>
        <h3>
            <span>Tags</span>
        </h3>
        <div id="tags">
            <?php
            foreach ($page->tags as $tag) {
                ?>
                <a
                    href="/search?search=<?=$tag->tag;?>"
                    title="Click to search based on this tag">&#35;<?= $tag->tag; ?></a>
                <?php
            }
            ?>
        </div>
        <?php
    }
    ?>
</div>