<?php
use Kytschi\Tengu\Controllers\Core\EmailController;
use Kytschi\Tengu\Controllers\Core\FormController;

$status = true;
if (isset($_POST['send'])) {
    try {
        $controller = new FormController();
        $controller->saveFormData($_POST);

        if ($valid = $this->tengu->captchaValidate($_POST['captcha'])) {
            $sent = false;
            if (
                !empty($_POST['name']) ||
                !empty($_POST['email']) ||
                !empty($_POST['message'])
            ) {
                $message = strip_tags($_POST['message']);
                $message .= "\nName: " . $_POST['name'];
                $message .= "\nPhone: " . (!empty($_POST['phone']) ? $_POST['phone'] : 'not set');

                $sent = (new EmailController())->send(
                    $_POST['name'],
                    $_POST['email'],
                    'Website contact from ' . $_POST['name'],
                    $message,
                    '',
                    '',
                    (!empty($_POST['phone']) ? $_POST['phone'] : '')
                );

                if ($sent) {
                    $controller->redirect($page->url . "?sent=true");
                } else {
                    $status = 'Failed to send the message';
                }
            }
        }
    } catch (\Exception $err) {
        $status = $err->getMessage();
    }
}
?>
<div id="page">
    <?php
    if (is_string($status)) {
        ?>
        <div class="content error">
            <h5>I'm but something went wrong...</h5>
            <p>
                <?= $status; ?>
            </p>
        </div>
        <p>&nbsp;</p>
        <?php
    }
    if (isset($_GET['sent'])) {
        ?>
        <div class="content">
            <h5>Thank you</h5>
            <p>
                We will be in touch shortly.
            </p>
        </div>
        <p>&nbsp;</p>
        <?php
    }
    ?>
    <h2><?= $page->name; ?></h2>
    <section>
        <?php
        if ($page->content) {
            echo $page->content;
        }
        ?>
        <form method="post">
            <div class="form">
                <div class="form-body">
                    <div class="form-group">
                        <span>Your name<i class="required">*</i></span>
                        <input 
                            class="form-control"
                            name="name" 
                            value="<?= !empty($_POST['name']) ? $_POST['name'] : ''; ?>" 
                            placeholder="Please enter your name">
                    </div>
                    <div class="form-group">
                        <span>Your email<i class="required">*</i></span>
                        <input 
                            class="form-control"
                            name="email" 
                            value="<?= !empty($_POST['email']) ? $_POST['email'] : ''; ?>" 
                            placeholder="Please enter your email">
                    </div>
                    <div class="form-group">
                        <span>Your number</span>
                        <input 
                            class="form-control"
                            name="phone" 
                            value="<?= !empty($_POST['phone']) ? $_POST['phone'] : ''; ?>" 
                            placeholder="Please enter your number if you like">
                    </div>
                    <div class="form-group">
                        <span>Your message<i class="required">*</i></span>
                        <textarea 
                            class="form-control"
                            rows="5" 
                            name="message" 
                            placeholder="What's your question or message?"><?= !empty($_POST['message']) ? $_POST['message'] : ''; ?></textarea>
                    </div>
                    <div class="form-group">
                        <span>Captcha<i class="required">*</i></span>
                        <?= $this->tengu->captcha(); ?>
                        <input name="_TSC" type="hidden" value="<?= FormController::generateTSC(); ?>">
                    </div>
                </div>
                <div class="form-footer">
                    <p><i class="required">*</i>&nbsp;required fields</p>
                    <button class="button" type="submit" name="send">Send</button>
                </div>
            </div>
        </form>
    </section>
</div>