<?php
use Kytschi\Tengu\Controllers\Core\EmailController;
use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\DateHelper;
use Kytschi\Tengu\Helpers\UrlHelper;
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="referrer" content="origin">
		<meta name="robots" content="<?= $page->robots; ?>">
        <meta name="description" content="<?= $page->meta_description; ?>">
        <meta name="keywords" content="<?= $page->meta_keywords; ?>">
        <meta name="author" content="<?= $page->meta_author; ?>">
		<meta name="revised" content="<?= DateHelper::meta($page->page_updated); ?>">

        <title><?= (!empty($page->name) ? $page->name . ' - ' : '')  . $this->tengu->settings->name;?></title>

        <link rel="stylesheet" href="<?= $this->tengu->theme->getCSS('bootstrap.min.css'); ?>">
        <link rel="stylesheet" href="<?= $this->tengu->theme->getCSS('theme.css'); ?>">
        <link rel="icon" href="<?= $this->tengu->theme->getAsset('imgs/favicon.ico'); ?>" sizes="64x64">

        <link rel="canonical" href="<?= $this->tengu->canonicalUrl(); ?>">
        <link rel="author" href="/humans.txt">

        <script src="<?= $this->tengu->theme->getAsset('js/plugins/jquery.min.js');?>"></script>
        <script src="<?= $this->tengu->theme->getAsset('js/plugins/popper.min.js');?>"></script>
        <script src="<?= $this->tengu->theme->getAsset('js/plugins/bootstrap.min.js');?>"></script>
    </head>
    <body <?= !empty($page->banner_image) ? 'style="background-image: url(' . $page->banner_image->url . ');"' : '' ?>>
        <div class="container-fluid">
            <div class="container">
                <header>
                    <nav id="menu" class="row m-0">
                        <div class="col-12 p-0">
                            <h1 class="float-left">
                                <a href="/" title="Go to home">
                                    <?= $this->tengu->settings->name; ?>
                                </a>
                            </h1>
                            <ul id="menu-nav" class="float-right">
                                <?php
                                if ($menu = $this->tengu->findMenu(['slug' => 'header'])) {
                                    foreach ($menu->category_items as $item) {
                                        ?>
                                        <li class="nav-item">
                                            <a
                                                href="<?= $item->link; ?>"
                                                class="nav-link<?= (UrlHelper::matches($item->link)) ? ' active' : '';?>"
                                                <?= !empty($item->new_window) ? 'target="_blank"' : ''; ?>
                                                title="Click to view the talk topic, <?= $item->name; ?>"
                                            >
                                                <?= $item->name; ?>
                                            </a>
                                        </li>
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                            <div id="menu-nav-mini">
                                <span class="nav-link" data-toggle="dropdown">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                                        <path d="M1 2.5A1.5 1.5 0 0 1 2.5 1h3A1.5 1.5 0 0 1 7 2.5v3A1.5 1.5 0 0 1 5.5 7h-3A1.5 1.5 0 0 1 1 5.5v-3zM2.5 2a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 1h3A1.5 1.5 0 0 1 15 2.5v3A1.5 1.5 0 0 1 13.5 7h-3A1.5 1.5 0 0 1 9 5.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zM1 10.5A1.5 1.5 0 0 1 2.5 9h3A1.5 1.5 0 0 1 7 10.5v3A1.5 1.5 0 0 1 5.5 15h-3A1.5 1.5 0 0 1 1 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3zm6.5.5A1.5 1.5 0 0 1 10.5 9h3a1.5 1.5 0 0 1 1.5 1.5v3a1.5 1.5 0 0 1-1.5 1.5h-3A1.5 1.5 0 0 1 9 13.5v-3zm1.5-.5a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 .5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5h-3z"/>
                                    </svg>
                                </span>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <?php
                                    if ($menu) {
                                        foreach ($menu->category_items as $item) {
                                            ?>
                                            <li class="nav-item">
                                                <a
                                                    href="<?= $item->link; ?>"
                                                    class="nav-link<?= (UrlHelper::matches($item->link)) ? ' active' : '';?>"
                                                    <?= !empty($item->new_window) ? 'target="_blank"' : ''; ?>
                                                    title="Click to view the talk topic, <?= $item->name; ?>"
                                                >
                                                    <?= $item->name; ?>
                                                </a>
                                            </li>
                                            <?php
                                        }
                                    }
                                    ?>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </header>
                <main>
                    <?= $this->getContent(); ?>
                </main>
                <footer>
                    <div class="row">
                        <div class="col-lg-4 col-md-6">
                            <div class="copyright">
                                &copy;<?= date('Y'); ?>
                                <?= !empty($this->tengu->settings->company_name) ? $this->tengu->settings->company_name : $this->tengu->settings->name; ?>
                            </div>
                            <div class="powered-by">
                                <a href="https://tengu.kytschi.com" target="_blank">
                                    Powered by Tengu
                                </a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6">
                            <ul>
                                <?php
                                if ($footer_menu = $this->tengu->findMenu(['slug' => 'footer'])) {
                                    foreach ($footer_menu->category_items as $item) {
                                        $link = $item->link;
                                        ?>
                                        <li class="nav-item">
                                            <a
                                                href="<?= $link; ?>"
                                                class="nav-link<?= (UrlHelper::matches($link)) ? ' active' : '';?>"
                                                <?= !empty($item->new_window) ? 'target="_blank"' : ''; ?>
                                                title="Click to view the page, <?= $item->name; ?>">
                                                <?= $item->name; ?>
                                            </a>
                                        </li>
                                        <?php
                                    }
                                }
                                ?>
                            </ul>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
	</body>
</html>
