<?php
use Kytschi\Tengu\Controllers\Core\FormController;
use Kytschi\Tengu\Helpers\UrlHelper;

$url = '/search';
$count = 0;
if (isset($results)) {
    $count = $results->total_items;
    $limits = [30,100,250];
    $limit = !empty($results->limit) ? intval($results->limit) : 30;
    if (!empty($_GET['limit']) && in_array(intval($_GET['limit']), $limits)) {
        $limit = intval($_GET['limit']);
    }

    $start = intval($results->current / 5) * 5;
    if ($start <= 0) {
        $start = 1;
    }

    $result_start = (($start - 1) * $limit) + 1;

    $end = $start + 4;
    $result_end = (($end - 1) * $limit) + 1;

    if ($end > $results->last) {
        $end = $results->last;
        $result_end = $results->total_items;
    }

    if ($result_end == 0) {
        $result_start = 0;
    }
} else {
    $results = null;
    $result_start = 0;
}
?>
<div id="page">
    <h2><?= $page->name; ?></h2>
    <?php
    if ($page->content) {
        ?>
        <section>
            <?= $page->content; ?>
        </section>
        <?php
    }
    ?>
    <form id="search" action="/search" method="get" class="row">
        <div class="col-12 mb-4">
            <input
                class="form-control"
                placeholder="What you looking for?"
                type="text"
                name="search"
                maxlength="255"
                value="<?= !empty($_GET['search']) ? FormController::cleanString($_GET['search']) : ''; ?>">
        </div>
        <div class="col-12">
        <?php
        if ($count) {
            ?>
            <div class="tiles">
                <?php
                foreach ($results->getItems() as $item) {
                    ?>
                    <div class="tile">
                        <h4><?= $item->name; ?></h4>
                        <?php
                        if ($item->cover_image) {
                            ?>
                            <p class="tile-img">
                                <img 
                                    src="<?=$item->cover_image->url;?>"
                                    title="<?= $item->name; ?>"
                                    alt="<?= $item->cover_image->label; ?>">
                            </p>
                            <?php
                        }
                        ?>
                        <p>
                            <?= $item->summary; ?>
                        </p>
                        <p>
                            <a 
                                href="<?= !empty($item->canonical_url) ? $item->canonical_url : $item->url; ?>"
                                class="button" 
                                <?= strpos($item->url, 'http') ? ' target="_blank"' : ''; ?>
                                title="I want to check out <?= $item->name; ?>">
                                Take me to it
                            </a>
                        </p>
                    </div>
                    <?php
                }
                ?>
            </div>
            <?php
        } else {
            if (isset($_GET['search'])) {
                ?>
                Sorry but nothing was found for that search query
                <?php
            }
        }
        ?>
        </div>
        <?php
        if ($result_start) {
            ?>
            <div class="col-12 mt-4 p-0">
                <ul class="pagination">
                    <li class="page-item previous <?= $results->current == $results->first ? ' disabled' : ''; ?>">
                        <a href="<?= UrlHelper::generate($url, ['page' => $results->current - 1 > $results->first ? $results->current - 1 : $results->first]); ?>" class="page-link">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z"/>
                            </svg>
                        </a>
                    </li>
                    <?php
                    for ($iLoop = $start; $iLoop <= $end; $iLoop++) {
                        ?>
                        <li class="page-item <?= $results->current == $iLoop ? 'active' :''; ?><?= $start == $end ? ' disabled text-muted' : ''; ?>">
                            <a href="<?= UrlHelper::generate($url, ['page' => $iLoop]); ?>" class="page-link"><?= $iLoop; ?></a>
                        </li>
                        <?php
                    }
                    ?>
                    <li class="page-item next <?= $results->current == $results->last ? ' disabled text-muted' : ''; ?>">
                        <a href="<?= UrlHelper::generate($url, ['page' => $results->current + 1 < $results->last ? $results->current + 1 : $results->last]); ?>" class="page-link">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chevron-right" viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
                            </svg>
                        </a>
                    </li>
                </ul>
            </div>
            <script src="/assets/js/core/pagination.js"></script>
            <?php
        }
        ?>
    </div>
</div>