<?php
use Kytschi\Tengu\Controllers\IndexController;
use Kytschi\Tengu\Helpers\DateHelper;

$pages = (new IndexController())->sitemapAction(true);
?>
<div id="page">
    <h2><?= $page->name; ?></h2>
    <?php
    if (!$pages->count()) {
        ?>
        Sorry but no sitemap
        <?php
    } else {
        ?>
        <div class="tiles">
            <?php
            foreach ($pages as $item) {
                ?>
                <div class="tile">
                    <h4><?= $item->name; ?></h4>
                    <?php
                    if ($item->cover_image) {
                        ?>
                        <p class="tile-img">
                            <img 
                                src="<?=$item->cover_image->url;?>"
                                title="<?= $item->name; ?>"
                                alt="<?= $item->cover_image->label; ?>">
                        </p>
                        <?php
                    }
                    ?>
                    <p>
                        <?= $item->summary; ?>
                    </p>
                    <p>
                        <a 
                            href="<?= !empty($item->canonical_url) ? $item->canonical_url : $item->url; ?>"
                            class="button" 
                            title="Show me about the <?= $item->name; ?> page">
                            show me more
                        </a>
                    </p>
                </div>
                <?php
            }
            ?>
        </div>
        <?php
    }
    ?>
</div>